AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TeamCFunction      
      Handler: src/index
      Runtime: nodejs8.10      
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: post