version: 0.2
phases:        
  build:
    commands:    
    - aws cloudformation package --template-file app-sam.yaml --s3-bucket ccl-training --output-template-file app-output_sam.yaml    
artifacts:
  files:
    - app-output_sam.yaml   
  discard-paths: yes