version: 0.2
env:
  variables:
    SERVERLESS_ACCESS_KEY : "AKQhVmAroyTTFvRc9LjyIv1AlP6DPhh3ufBAtMoJkBcuC"
phases:        
  build:
    commands:    
    - npm install -g serverless
    - npm install    
    - serverless deploy
artifacts:
  files:
    - app-output_sam.yaml   
  discard-paths: yes